import xml.etree.ElementTree as ET
from hashlib import sha256

xml = """<?xml version='1.0' encoding='utf-8'?>
<users>
    <user>
        <username>Anthony</username>
        <password>65e98b092209f2a3a5ea892985fc4294e75b64012e0b12a01226ef1e895c8747</password>
    </user>
</users>"""

tree = ET.ElementTree(ET.fromstring(xml))

class i_need_more_boolets():
    def __init__(self, xml_data):
        import tkinter as tk
        import xml.etree.ElementTree as ET

        root = tk.Tk()
        root.title("Football Team Information")

        # Parse the XML data
        root_xml = ET.fromstring(xml_data)
        print(xml_data)
        print(root_xml)

        # Create labels and display data
        labels = {
            'City': root_xml.find('city').text,
            'Team Name': root_xml.find('teamname').text,
            'Middle Name': root_xml.find('middle_name').text,
            'Venue': root_xml.find('venue').text,
            'Rank': root_xml.find('league_results/rank').text,
            'Played': root_xml.find('league_results/played').text,
            'Won': root_xml.find('league_results/won').text,
            'Drawn': root_xml.find('league_results/drawn').text,
            'Lost': root_xml.find('league_results/lost').text,
            'Goal Difference': root_xml.find('league_results/goal_difference').text,
            'Points': root_xml.find('league_results/points').text
        }

        for i, (label_text, value_text) in enumerate(labels.items()):
            label = tk.Label(root, text=label_text)
            label.grid(row=i, column=0, padx=10, pady=5, sticky='w')

            value = tk.Label(root, text=value_text)
            value.grid(row=i, column=1, padx=10, pady=5, sticky='e')

        root.mainloop()

class gui0():
    def __init__(window):
        # This file was generated by the Tkinter Designer by Parth Jadhav
        # https://github.com/ParthJadhav/Tkinter-Designer

        from pathlib import Path

        # from tkinter import *
        # Explicit imports to satisfy Flake8
        from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ace42\OneDrive\Desktop\build\assets\frame0")
        tree = ET.parse('./assets/MCI.xml')
        root = tree.getroot()
        ET.dump(root)
        print(root)
        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)
        
        def searchFunction(event):
            search = entry_1.get()
            print(search)
            for team in root:
                teamname = team.find('teamname').text
                if teamname in search:
                   i_need_more_boolets(ET.tostring(team, encoding='unicode'))

        def logout(window):
            window.destroy()
            gui00()

        window = Tk()

        window.geometry("1440x960")
        window.configure(bg = "#FFFFFF")

        canvas = Canvas(
            window,
            bg = "#FFFFFF",
            height = 960,
            width = 1440,
            bd = 0,
            highlightthickness = 0,
            relief = "ridge"
        )

        canvas.place(x = 0, y = 0)
        canvas.create_rectangle(
            0.0,
            28.0,
            1440.0,
            810.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_rectangle(
            0.0,
            28.0,
            1440.0,
            87.0,
            fill="#00225C",
            outline="")

        canvas.create_rectangle(
            2.5,
            172.54750061035156,
            1440.0,
            174.95249938964844,
            fill="#000000",
            outline="")

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: nextwindow(),
            relief="flat"
        )
        button_1.place(
            x=1364.0,
            y=106.0,
            width=48.0,
            height=48.0
        )

        canvas.create_text(
            752.0,
            186.0,
            anchor="nw",
            text="Top 5 assists",
            fill="#000000",
            font=("RobotoRoman Bold", 20 * -1)
        )

        canvas.create_text(
            1102.0,
            190.0,
            anchor="nw",
            text="Top 5 yellow cards",
            fill="#000000",
            font=("RobotoRoman Bold", 20 * -1)
        )

        button_image_2 = PhotoImage(
            file=relative_to_assets("button_2.png"))
        button_2 = Button(
            image=button_image_2,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_2 clicked"),
            relief="flat"
        )
        button_2.place(
            x=524.0,
            y=117.0,
            width=86.0,
            height=32.0
        )

        button_image_3 = PhotoImage(
            file=relative_to_assets("button_3.png"))
        button_3 = Button(
            image=button_image_3,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_3 clicked"),
            relief="flat"
        )
        button_3.place(
            x=682.0,
            y=116.0,
            width=83.0,
            height=32.0
        )

        button_image_4 = PhotoImage(
            file=relative_to_assets("button_4.png"))
        button_4 = Button(
            image=button_image_4,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: print("button_4 clicked"),
            relief="flat"
        )
        button_4.place(
            x=837.0,
            y=116.0,
            width=79.0,
            height=32.0
        )

        canvas.create_rectangle(
            0.0,
            28.0,
            175.0,
            152.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            19.0,
            121.0,
            anchor="nw",
            text="TRACKER",
            fill="#00225D",
            font=("Alatsi Regular", 23 * -1)
        )

        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas.create_image(
            84.784423828125,
            78.0,
            image=image_image_1
        )

        canvas.create_text(
            77.0,
            195.0,
            anchor="nw",
            text="Team Rank",
            fill="#000000",
            font=("RobotoRoman Bold", 20 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            254.7698974609375,
            297.0,
            301.6349411010742,
            fill="#FFFFFF",
            outline="")

        image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = canvas.create_image(
            171.0,
            278.0,
            image=image_image_2
        )

        canvas.create_text(
            206.2982635498047,
            270.3915710449219,
            anchor="nw",
            text="Man City",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_text(
            145.0,
            232.0,
            anchor="nw",
            text="Team",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            78.0,
            233.0,
            anchor="nw",
            text="Rank",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            84.0,
            268.0,
            anchor="nw",
            text="1",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            85.0,
            321.0,
            anchor="nw",
            text="2",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            85.0,
            377.0,
            anchor="nw",
            text="3",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            84.0,
            438.0,
            anchor="nw",
            text="4",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            84.0,
            494.0,
            anchor="nw",
            text="5",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            84.0,
            550.0,
            anchor="nw",
            text="6",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            84.0,
            602.0,
            anchor="nw",
            text="7",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            84.0,
            658.0,
            anchor="nw",
            text="8",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            85.0,
            717.0,
            anchor="nw",
            text="9",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            82.0,
            776.0,
            anchor="nw",
            text="10",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            310.4646301269531,
            297.0,
            357.32967376708984,
            fill="#FFFFFF",
            outline="")

        image_image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = canvas.create_image(
            171.0,
            334.0,
            image=image_image_3
        )

        canvas.create_text(
            206.2982635498047,
            326.0863037109375,
            anchor="nw",
            text="Arsenal",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            366.1593017578125,
            297.0,
            413.0243453979492,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            206.2982635498047,
            381.7809753417969,
            anchor="nw",
            text="Man Utd",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            423.8916320800781,
            297.0,
            470.75667572021484,
            fill="#FFFFFF",
            outline="")

        image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = canvas.create_image(
            170.0,
            448.0,
            image=image_image_4
        )

        canvas.create_text(
            206.2982635498047,
            439.5133056640625,
            anchor="nw",
            text="Newcastle",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            480.2655029296875,
            297.0,
            527.1305465698242,
            fill="#FFFFFF",
            outline="")

        image_image_5 = PhotoImage(
            file=relative_to_assets("image_5.png"))
        image_5 = canvas.create_image(
            171.0,
            504.0,
            image=image_image_5
        )

        canvas.create_text(
            206.2982635498047,
            495.8871765136719,
            anchor="nw",
            text="Liverpool ",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            535.9601440429688,
            297.0,
            582.8251953125,
            fill="#FFFFFF",
            outline="")

        image_image_6 = PhotoImage(
            file=relative_to_assets("image_6.png"))
        image_6 = canvas.create_image(
            168.40350341796875,
            560.714599609375,
            image=image_image_6
        )

        canvas.create_text(
            206.2982635498047,
            551.5818481445312,
            anchor="nw",
            text="Brighton ",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            591.6548461914062,
            297.0,
            638.5198974609375,
            fill="#FFFFFF",
            outline="")

        image_image_7 = PhotoImage(
            file=relative_to_assets("image_7.png"))
        image_7 = canvas.create_image(
            168.40350341796875,
            616.4092407226562,
            image=image_image_7
        )

        canvas.create_text(
            206.2982635498047,
            607.2764892578125,
            anchor="nw",
            text="Aston Villa",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            648.7080078125,
            297.0,
            695.5730590820312,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            206.2982635498047,
            664.3297119140625,
            anchor="nw",
            text="Tottenham",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            705.0818481445312,
            297.0,
            751.9468994140625,
            fill="#FFFFFF",
            outline="")

        image_image_8 = PhotoImage(
            file=relative_to_assets("image_8.png"))
        image_8 = canvas.create_image(
            168.40350341796875,
            729.8363037109375,
            image=image_image_8
        )

        canvas.create_text(
            206.2982635498047,
            720.7035522460938,
            anchor="nw",
            text="Brentford",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            145.1871337890625,
            762.1349487304688,
            297.0,
            809.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            206.2982635498047,
            777.7566528320312,
            anchor="nw",
            text="Fulham",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        image_image_9 = PhotoImage(
            file=relative_to_assets("image_9.png"))
        image_9 = canvas.create_image(
            170.0,
            390.0,
            image=image_image_9
        )

        image_image_10 = PhotoImage(
            file=relative_to_assets("image_10.png"))
        image_10 = canvas.create_image(
            167.0,
            672.0,
            image=image_image_10
        )

        image_image_11 = PhotoImage(
            file=relative_to_assets("image_11.png"))
        image_11 = canvas.create_image(
            168.0,
            786.0,
            image=image_image_11
        )

        button_image_5 = PhotoImage(
            file=relative_to_assets("button_5.png"))
        button_5 = Button(
            image=button_image_5,
            borderwidth=0,
            highlightthickness=0,
            command=lambda: logout(window),
            relief="flat"
        )
        button_5.place(
            x=1251.0,
            y=116.0,
            width=96.0,
            height=32.0
        )

        canvas.create_text(
            382.0,
            186.0,
            anchor="nw",
            text="Top 5 goals",
            fill="#000000",
            font=("RobotoRoman Bold", 20 * -1)
        )

        canvas.create_rectangle(
            452.0,
            252.0,
            642.0,
            300.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            503.0,
            264.0,
            anchor="nw",
            text="Erling Haaland (MCI)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            452.0,
            330.0,
            642.0,
            378.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            526.0,
            346.0,
            anchor="nw",
            text="Harry Kane (ToT)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            452.0,
            409.0,
            642.0,
            457.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            525.0,
            426.0,
            anchor="nw",
            text="Ivan Toney (BRE)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            452.0,
            487.0,
            642.0,
            535.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            497.0,
            502.0,
            anchor="nw",
            text="Mohamed Salah (LIV)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            452.0,
            568.0,
            642.0,
            616.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            500.0,
            585.0,
            anchor="nw",
            text="Callum Wilson (NEW)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_text(
            390.0,
            257.0,
            anchor="nw",
            text="36",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            390.0,
            332.0,
            anchor="nw",
            text="30",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            390.0,
            409.0,
            anchor="nw",
            text="20",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            390.0,
            493.0,
            anchor="nw",
            text="19",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            390.0,
            571.0,
            anchor="nw",
            text="18",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            452.0,
            219.0,
            anchor="nw",
            text="Players",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            382.0,
            219.0,
            anchor="nw",
            text="Goals",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        image_image_12 = PhotoImage(
            file=relative_to_assets("image_12.png"))
        image_12 = canvas.create_image(
            480.0,
            276.0,
            image=image_image_12
        )

        image_image_13 = PhotoImage(
            file=relative_to_assets("image_13.png"))
        image_13 = canvas.create_image(
            478.0,
            353.0,
            image=image_image_13
        )

        image_image_14 = PhotoImage(
            file=relative_to_assets("image_14.png"))
        image_14 = canvas.create_image(
            478.0,
            432.0,
            image=image_image_14
        )

        image_image_15 = PhotoImage(
            file=relative_to_assets("image_15.png"))
        image_15 = canvas.create_image(
            477.0,
            511.0,
            image=image_image_15
        )

        image_image_16 = PhotoImage(
            file=relative_to_assets("image_16.png"))
        image_16 = canvas.create_image(
            477.0,
            593.0,
            image=image_image_16
        )

        canvas.create_rectangle(
            823.0,
            252.0,
            1013.0,
            300.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            863.0,
            268.0,
            anchor="nw",
            text="Kevin De Bruyne (MCI)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            823.0,
            330.0,
            1013.0,
            378.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            871.0,
            346.0,
            anchor="nw",
            text="Mohamed Salah (LIV)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            823.0,
            409.0,
            1013.0,
            457.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            885.0,
            419.0,
            anchor="nw",
            text="Leonardo Trossard (ARS)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            823.0,
            487.0,
            1013.0,
            535.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            876.0565795898438,
            502.3043518066406,
            anchor="nw",
            text="Bukayo Saka (ARS)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            823.0,
            568.0,
            1013.0,
            616.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            876.0565795898438,
            583.3043212890625,
            anchor="nw",
            text="Michael Olise (CRY)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_text(
            765.0,
            258.0,
            anchor="nw",
            text="16",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            765.0,
            333.0,
            anchor="nw",
            text="12",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            765.0,
            410.0,
            anchor="nw",
            text="12",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            765.0,
            494.0,
            anchor="nw",
            text="11",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            765.0,
            572.0,
            anchor="nw",
            text="11",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            823.0,
            219.0,
            anchor="nw",
            text="Players",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_text(
            752.0,
            219.0,
            anchor="nw",
            text="Assists",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        image_image_17 = PhotoImage(
            file=relative_to_assets("image_17.png"))
        image_17 = canvas.create_image(
            848.0,
            354.0,
            image=image_image_17
        )

        image_image_18 = PhotoImage(
            file=relative_to_assets("image_18.png"))
        image_18 = canvas.create_image(
            848.0,
            512.0,
            image=image_image_18
        )

        image_image_19 = PhotoImage(
            file=relative_to_assets("image_19.png"))
        image_19 = canvas.create_image(
            848.0,
            592.0,
            image=image_image_19
        )

        canvas.create_text(
            1115.0,
            258.0,
            anchor="nw",
            text="14",
            fill="#000000",
            font=("RobotoRoman Bold", 14 * -1)
        )

        canvas.create_text(
            1115.0,
            333.0,
            anchor="nw",
            text="12",
            fill="#000000",
            font=("RobotoRoman Bold", 14 * -1)
        )

        canvas.create_text(
            1115.0,
            410.0,
            anchor="nw",
            text="12",
            fill="#000000",
            font=("RobotoRoman Bold", 14 * -1)
        )

        canvas.create_text(
            1115.0,
            494.0,
            anchor="nw",
            text="11",
            fill="#000000",
            font=("RobotoRoman Bold", 14 * -1)
        )

        canvas.create_text(
            1115.0,
            572.0,
            anchor="nw",
            text="11",
            fill="#000000",
            font=("RobotoRoman Bold", 14 * -1)
        )

        canvas.create_text(
            1105.0,
            219.0,
            anchor="nw",
            text="Cards",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        canvas.create_rectangle(
            1162.0,
            252.0,
            1352.0,
            300.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            1215.0,
            267.0,
            anchor="nw",
            text="Joao Palhinha (FUL)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            1162.0,
            330.0,
            1352.0,
            378.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            1215.0,
            345.0,
            anchor="nw",
            text="Ruben Neves (WLV)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            1162.0,
            409.0,
            1352.0,
            457.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            1236.0,
            424.0,
            anchor="nw",
            text="Joelinton (NEW)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            1162.0,
            487.0,
            1352.0,
            535.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            1258.0,
            504.0,
            anchor="nw",
            text="Fabinho (LIV)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_rectangle(
            1162.0,
            568.0,
            1352.0,
            616.0,
            fill="#FFFFFF",
            outline="")

        canvas.create_text(
            1224.0,
            583.0,
            anchor="nw",
            text="Adam Smith (BOU)",
            fill="#000000",
            font=("Inter", 14 * -1)
        )

        canvas.create_text(
            1162.0,
            219.0,
            anchor="nw",
            text="Players",
            fill="#000000",
            font=("RobotoRoman Bold", 16 * -1)
        )

        image_image_20 = PhotoImage(
            file=relative_to_assets("image_20.png"))
        image_20 = canvas.create_image(
            1187.0,
            276.0,
            image=image_image_20
        )

        image_image_21 = PhotoImage(
            file=relative_to_assets("image_21.png"))
        image_21 = canvas.create_image(
            1187.0,
            354.0,
            image=image_image_21
        )

        image_image_22 = PhotoImage(
            file=relative_to_assets("image_22.png"))
        image_22 = canvas.create_image(
            1187.0,
            433.0,
            image=image_image_22
        )

        image_image_23 = PhotoImage(
            file=relative_to_assets("image_23.png"))
        image_23 = canvas.create_image(
            844.0,
            276.0,
            image=image_image_23
        )

        image_image_24 = PhotoImage(
            file=relative_to_assets("image_24.png"))
        image_24 = canvas.create_image(
            848.0,
            433.0,
            image=image_image_24
        )

        image_image_25 = PhotoImage(
            file=relative_to_assets("image_25.png"))
        image_25 = canvas.create_image(
            1187.0,
            511.0,
            image=image_image_25
        )

        image_image_26 = PhotoImage(
            file=relative_to_assets("image_26.png"))
        image_26 = canvas.create_image(
            1187.0,
            592.0,
            image=image_image_26
        )

        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas.create_image(
            311.0,
            132.0,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_1.place(
            x=206.0,
            y=104.0,
            width=210.0,
            height=54.0
        )
        entry_1.bind('<Return>', searchFunction)
        image_image_27 = PhotoImage(
            file=relative_to_assets("image_27.png"))
        image_27 = canvas.create_image(
            230.0,
            133.0,
            image=image_image_27
        )
        window.resizable(False, False)
        window.mainloop()

class gui00():
    def __init__(window):
        # This file was generated by the Tkinter Designer by Parth Jadhav
        # https://github.com/ParthJadhav/Tkinter-Designer


        from pathlib import Path

        # from tkinter import *
        # Explicit imports to satisfy Flake8
        from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage, messagebox


        OUTPUT_PATH = Path(__file__).parent
        ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ace42\OneDrive\Documents\build\assets\frame0")


        def relative_to_assets(path: str) -> Path:
            return ASSETS_PATH / Path(path)

        def homewindow(window):

            userName = entry_2.get()
            passwordinp = entry_1.get()
            print(userName, passwordinp)

            authenticated = False

            root = tree.getroot()

            for users in root.findall('user'):
                password = users.find("password").text
                username = users.find("username").text

                if username == userName and password == sha256(passwordinp.encode('utf-8')).hexdigest():
                    authenticated = True
                    break

            if authenticated:
                window.destroy()
                gui0()
                print("Access granted")
            else:
                messagebox.showinfo("Authentication Failed", "Try again")
            
        window = Tk()

        window.geometry("1440x810")
        window.configure(bg = "#FFFFFF")


        canvas1 = Canvas(
            window,
            bg = "#FFFFFF",
            height = 810,
            width = 1440,
            bd = 0,
            highlightthickness = 10,
            relief = "ridge"
        )

        canvas1.place(x = 0, y = 0)
        image_image_1 = PhotoImage(
            file=relative_to_assets("image_1.png"))
        image_1 = canvas1.create_image(
            720.0,
            405.0,
            image=image_image_1
        )

        canvas1.create_rectangle(
            566.0,
            308.0,
            902.0,
            598.0,
            fill="#36343B",
            outline="")

        entry_image_1 = PhotoImage(
            file=relative_to_assets("entry_1.png"))
        entry_bg_1 = canvas1.create_image(
            734.0,
            505.0,
            image=entry_image_1
        )
        entry_1 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0,
            show="*"
        )
        entry_1.place(
            x=629.0,
            y=477.0,
            width=210.0,
            height=54.0
        )

        entry_image_2 = PhotoImage(
            file=relative_to_assets("entry_2.png"))
        entry_bg_2 = canvas1.create_image(
            734.0,
            407.0,
            image=entry_image_2
        )
        entry_2 = Entry(
            bd=0,
            bg="#FFFFFF",
            fg="#000716",
            highlightthickness=0
        )
        entry_2.place(
            x=629.0,
            y=379.0,
            width=210.0,
            height=54.0
        )

        canvas1.create_text(
            662.0,
            337.0,
            anchor="nw",
            text="Your Account",
            fill="#FFFFFF",
            font=("RobotoRoman Bold", 24 * -1)
        )

        button_image_1 = PhotoImage(
            file=relative_to_assets("button_1.png"))
        button_1 = Button(
            image=button_image_1,
            borderwidth=0,
            highlightthickness=0,
            command=lambda : homewindow(window),
            relief="flat"
        )
        button_1.place(
            x=689.0,
            y=548.0,
            width=90.0,
            height=40.0
        )

        canvas1.create_text(
            482.0,
            760.0,
            anchor="nw",
            text="In collaboration with ",
            fill="#FFFFFF",
            font=("RobotoRoman Regular", 18 * -1)
        )

        image_image_2 = PhotoImage(
            file=relative_to_assets("image_2.png"))
        image_2 = canvas1.create_image(
            958.0,
            769.0,
            image=image_image_2
        )

        image_image_3 = PhotoImage(
            file=relative_to_assets("image_3.png"))
        image_3 = canvas1.create_image(
            784.0,
            770.0,
            image=image_image_3
        )

        canvas1.create_text(
            629.0,
            361.0,
            anchor="nw",
            text="Name",
            fill="#D0BCFF",
            font=("Roboto Regular", 12 * -1)
        )

        canvas1.create_text(
            629.0,
            450.0,
            anchor="nw",
            text="Password",
            fill="#D0BCFF",
            font=("Roboto Regular", 12 * -1)
            
        )
        
        canvas1.create_rectangle(
            557.0,
            25.0,
            911.0,
            268.0,
            fill="#FFFFFF",
            outline="")

        image_image_4 = PhotoImage(
            file=relative_to_assets("image_4.png"))
        image_4 = canvas1.create_image(
            748.0,
            117.0,
            image=image_image_4
        )

        canvas1.create_text(
            615.0,
            210.0,
            anchor="nw",
            text="TRACKER",
            fill="#00225D",
            font=("Alatsi Regular", 46 * -1)
        )
        window.resizable(False, False)
        window.mainloop()

gui00window = gui00()

from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ace42\OneDrive - Department of Education\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)

def logout(window):
            window.destroy()
            gui00()
            
window = Tk()

window.geometry("1440x838")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 838,
    width = 1440,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    14.0,
    1440.0,
    824.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    975.0,
    687.0,
    anchor="nw",
    text="Chelsea have reportedly opened talks to sign Neymar.",
    fill="#1D1B20",
    font=("Roboto Regular", 16 * -1)
)

canvas.create_text(
    519.0,
    711.0,
    anchor="nw",
    text="Liverpool's new number 10",
    fill="#1D1B20",
    font=("Roboto Regular", 16 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=1346.0,
    y=203.0,
    width=42.0,
    height=40.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=858.0,
    y=203.0,
    width=42.0,
    height=40.0
)

canvas.create_text(
    101.0,
    265.0,
    anchor="nw",
    text="Sky Sports",
    fill="#1D1B20",
    font=("Roboto Medium", 16 * -1)
)

canvas.create_text(
    101.0,
    293.0,
    anchor="nw",
    text="@SkySports",
    fill="#1D1B20",
    font=("Roboto Regular", 14 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    46.0,
    289.0,
    image=image_image_1
)

canvas.create_text(
    25.0,
    717.0,
    anchor="nw",
    text="What a first season at Manchester City for Erling Haaland",
    fill="#1D1B20",
    font=("Roboto Regular", 16 * -1)
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=352.0,
    y=273.0,
    width=42.0,
    height=40.0
)

canvas.create_text(
    101.0,
    265.0,
    anchor="nw",
    text="Sky Sports",
    fill="#1D1B20",
    font=("Roboto Medium", 16 * -1)
)

canvas.create_text(
    101.0,
    293.0,
    anchor="nw",
    text="@SkySports",
    fill="#1D1B20",
    font=("Roboto Regular", 14 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    46.0,
    289.0,
    image=image_image_2
)

canvas.create_text(
    601.0,
    203.0,
    anchor="nw",
    text="Sky Sports",
    fill="#1D1B20",
    font=("Roboto Medium", 16 * -1)
)

canvas.create_text(
    601.0,
    231.0,
    anchor="nw",
    text="@SkySports",
    fill="#1D1B20",
    font=("Roboto Regular", 14 * -1)
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    546.0,
    227.0,
    image=image_image_3
)

canvas.create_text(
    601.0,
    203.0,
    anchor="nw",
    text="Sky Sports",
    fill="#1D1B20",
    font=("Roboto Medium", 16 * -1)
)

canvas.create_text(
    601.0,
    231.0,
    anchor="nw",
    text="@SkySports",
    fill="#1D1B20",
    font=("Roboto Regular", 14 * -1)
)

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    546.0,
    227.0,
    image=image_image_4
)

canvas.create_text(
    1054.0,
    203.0,
    anchor="nw",
    text="Sky Sports",
    fill="#1D1B20",
    font=("Roboto Medium", 16 * -1)
)

canvas.create_text(
    1054.0,
    231.0,
    anchor="nw",
    text="@SkySports",
    fill="#1D1B20",
    font=("Roboto Regular", 14 * -1)
)

image_image_5 = PhotoImage(
    file=relative_to_assets("image_5.png"))
image_5 = canvas.create_image(
    999.0,
    227.0,
    image=image_image_5
)

canvas.create_text(
    1054.0,
    203.0,
    anchor="nw",
    text="Sky Sports",
    fill="#1D1B20",
    font=("Roboto Medium", 16 * -1)
)

canvas.create_text(
    1054.0,
    231.0,
    anchor="nw",
    text="@SkySports",
    fill="#1D1B20",
    font=("Roboto Regular", 14 * -1)
)

image_image_6 = PhotoImage(
    file=relative_to_assets("image_6.png"))
image_6 = canvas.create_image(
    999.0,
    227.0,
    image=image_image_6
)

image_image_7 = PhotoImage(
    file=relative_to_assets("image_7.png"))
image_7 = canvas.create_image(
    1186.0,
    462.0,
    image=image_image_7
)

image_image_8 = PhotoImage(
    file=relative_to_assets("image_8.png"))
image_8 = canvas.create_image(
    711.0,
    474.0,
    image=image_image_8
)

image_image_9 = PhotoImage(
    file=relative_to_assets("image_9.png"))
image_9 = canvas.create_image(
    208.0,
    506.0,
    image=image_image_9
)

canvas.create_text(
    22.0,
    186.0,
    anchor="nw",
    text="Trending News",
    fill="#000000",
    font=("RobotoRoman Bold", 22 * -1)
)

canvas.create_rectangle(
    0.0,
    28.0,
    1440.0,
    87.0,
    fill="#00225C",
    outline="")

canvas.create_rectangle(
    2.5,
    172.54750061035156,
    1440.0,
    174.95249938964844,
    fill="#000000",
    outline="")

button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_4 clicked"),
    relief="flat"
)
button_4.place(
    x=1364.0,
    y=106.0,
    width=48.0,
    height=48.0
)

button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_5 clicked"),
    relief="flat"
)
button_5.place(
    x=524.0,
    y=117.0,
    width=86.0,
    height=32.0
)

button_image_6 = PhotoImage(
    file=relative_to_assets("button_6.png"))
button_6 = Button(
    image=button_image_6,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_6 clicked"),
    relief="flat"
)
button_6.place(
    x=682.0,
    y=116.0,
    width=83.0,
    height=32.0
)

button_image_7 = PhotoImage(
    file=relative_to_assets("button_7.png"))
button_7 = Button(
    image=button_image_7,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_7 clicked"),
    relief="flat"
)
button_7.place(
    x=837.0,
    y=116.0,
    width=79.0,
    height=32.0
)

canvas.create_rectangle(
    0.0,
    28.0,
    175.0,
    152.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    19.0,
    121.0,
    anchor="nw",
    text="TRACKER",
    fill="#00225D",
    font=("Alatsi Regular", 23 * -1)
)

image_image_10 = PhotoImage(
    file=relative_to_assets("image_10.png"))
image_10 = canvas.create_image(
    84.784423828125,
    78.0,
    image=image_image_10
)

button_image_8 = PhotoImage(
    file=relative_to_assets("button_8.png"))
button_8 = Button(
    image=button_image_8,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: logout(window),
    relief="flat"
)
button_8.place(
    x=1251.0,
    y=116.0,
    width=96.0,
    height=32.0
)

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    311.0,
    132.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=206.0,
    y=104.0,
    width=210.0,
    height=54.0
)

image_image_11 = PhotoImage(
    file=relative_to_assets("image_11.png"))
image_11 = canvas.create_image(
    230.0,
    133.0,
    image=image_image_11
)
window.resizable(False, False)
window.mainloop()
