
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\ace42\OneDrive\Desktop\build\assets\frame1")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("1920x1080")
window.configure(bg = "#FFFFFF")


canvas = Canvas(
    window,
    bg = "#FFFFFF",
    height = 1080,
    width = 1920,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    960.0,
    563.0,
    image=image_image_1
)

canvas.create_rectangle(
    753.0,
    495.0,
    1203.0,
    895.0,
    fill="#36343B",
    outline="")

entry_image_1 = PhotoImage(
    file=relative_to_assets("entry_1.png"))
entry_bg_1 = canvas.create_image(
    973.0,
    726.0,
    image=entry_image_1
)
entry_1 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_1.place(
    x=868.0,
    y=698.0,
    width=210.0,
    height=54.0
)

entry_image_2 = PhotoImage(
    file=relative_to_assets("entry_2.png"))
entry_bg_2 = canvas.create_image(
    973.0,
    639.0,
    image=entry_image_2
)
entry_2 = Entry(
    bd=0,
    bg="#FFFFFF",
    fg="#000716",
    highlightthickness=0
)
entry_2.place(
    x=868.0,
    y=611.0,
    width=210.0, 
    height=54.0
)

canvas.create_text(
    886.0,
    546.0,
    anchor="nw",
    text="Your Account",
    fill="#FFFFFF",
    font=("RobotoRoman Bold", 26 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=928.0,
    y=794.0,
    width=90.0,
    height=40.0
)

canvas.create_text(
    729.0,
    1046.0,
    anchor="nw",
    text="In collaboration with ",
    fill="#FFFFFF",
    font=("RobotoRoman Regular", 18 * -1)
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    1175.0,
    1059.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    1013.0,
    1057.0,
    image=image_image_3
)

canvas.create_text(
    868.0,
    589.0,
    anchor="nw",
    text="Name",
    fill="#D0BCFF",
    font=("Roboto Regular", 12 * -1)
)

canvas.create_text(
    868.0,
    679.0,
    anchor="nw",
    text="Password",
    fill="#D0BCFF",
    font=("Roboto Regular", 12 * -1)
)

canvas.create_rectangle(
    767.0,
    59.0,
    1203.0,
    358.0,
    fill="#FFFFFF",
    outline="")

image_image_4 = PhotoImage(
    file=relative_to_assets("image_4.png"))
image_4 = canvas.create_image(
    971.0,
    163.0,
    image=image_image_4
)

canvas.create_text(
    831.0,
    263.0,
    anchor="nw",
    text="TRACKER",
    fill="#00225D",
    font=("Alatsi Regular", 46 * -1)
)
window.resizable(True, True)
window.mainloop()
